import type { Tournament } from '@/lib/supabase/types'

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 'dev-1',
    name: 'XMUM Premier League',
    description: null,
    location: 'XMUM Sports Hall',
    start_date: '2026-05-10',
    end_date: '2026-05-17',
    format: 'round_robin',
    points_win: 3,
    points_draw: 1,
    points_loss: 0,
    status: 'active',
    first_match_scheduled_at: '2026-05-10T09:00:00+08:00',
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-10T00:00:00Z',
    halftime_enabled: true,
    minutes_per_half: 45,
    halftime_minutes: 15,
    extra_time_minutes: null,
    penalty_shootout_enabled: false,
    require_goal_player: false,
    num_groups: null,
    teams_per_group: null,
    advance_per_group: null,
    knockout_start_round: null,
    seeding_method: null,
    min_players_per_team: 11,
  },
  {
    id: 'dev-2',
    name: 'Dev Cup 2026',
    description: null,
    location: 'Field B',
    start_date: '2026-05-20',
    end_date: '2026-05-22',
    format: 'knockout',
    points_win: 3,
    points_draw: 1,
    points_loss: 0,
    status: 'setup',
    first_match_scheduled_at: null,
    created_at: '2026-05-05T00:00:00Z',
    updated_at: '2026-05-05T00:00:00Z',
    halftime_enabled: true,
    minutes_per_half: 45,
    halftime_minutes: 15,
    extra_time_minutes: null,
    penalty_shootout_enabled: false,
    require_goal_player: false,
    num_groups: null,
    teams_per_group: null,
    advance_per_group: null,
    knockout_start_round: null,
    seeding_method: null,
    min_players_per_team: 11,
  },
]
