/* Home page data — multiple tournaments across campus */
window.HOME = {
  org: "Eastside University Sports",
  season: "Spring 2026",

  tournaments: [
    {
      id: "eastside-cup",
      name: "Eastside University Cup",
      edition: "Spring 2026",
      status: "live",
      accent: "#A3E635",
      format: "8 teams · Groups + Knockout",
      sport: "11-a-side",
      venue: "North Field",
      teams: 8,
      matchesLive: 3,
      progress: "Quarterfinals",
      featured: { home: "THU", homeColor: "#DC2626", away: "BLZ", awayColor: "#F59E0B", hs: 2, as: 1, min: 67 },
      href: "Live Tournament.html",
    },
    {
      id: "inter-hostel",
      name: "Inter-Hostel League",
      edition: "Spring 2026",
      status: "live",
      accent: "#38BDF8",
      format: "12 teams · Round robin",
      sport: "11-a-side",
      venue: "Fields 1–3",
      teams: 12,
      matchesLive: 2,
      progress: "Matchday 6 of 11",
      featured: { home: "BLK", homeColor: "#0891B2", away: "RDG", awayColor: "#DB2777", hs: 0, as: 0, min: 21 },
      href: "Live Tournament.html",
    },
    {
      id: "womens-premier",
      name: "Women's Campus Premier",
      edition: "Spring 2026",
      status: "live",
      accent: "#FB923C",
      format: "6 teams · Double round robin",
      sport: "11-a-side",
      venue: "South Field",
      teams: 6,
      matchesLive: 1,
      progress: "Matchday 8 of 10",
      featured: { home: "VLT", homeColor: "#7C3AED", away: "STM", awayColor: "#2563EB", hs: 3, as: 2, min: 78 },
      href: "Live Tournament.html",
    },
    {
      id: "freshers-5s",
      name: "Freshers' 5-a-side",
      edition: "Spring 2026",
      status: "upcoming",
      accent: "#A3E635",
      format: "16 teams · Straight knockout",
      sport: "5-a-side",
      venue: "Indoor Arena",
      teams: 16,
      startsIn: "Starts in 3 days",
      startDate: "Jun 10",
      href: "Live Tournament.html",
    },
    {
      id: "faculty-friendly",
      name: "Faculty Friendly Cup",
      edition: "Spring 2026",
      status: "upcoming",
      accent: "#F59E0B",
      format: "4 teams · Mini-league",
      sport: "7-a-side",
      venue: "North Field",
      teams: 4,
      startsIn: "Starts in 9 days",
      startDate: "Jun 16",
      href: "Live Tournament.html",
    },
    {
      id: "winter-futsal",
      name: "Winter Futsal Classic",
      edition: "Winter 2025",
      status: "finished",
      accent: "#6F7A65",
      format: "10 teams · Groups + Knockout",
      sport: "Futsal",
      venue: "Indoor Arena",
      teams: 10,
      champion: "Thunderhawks",
      championColor: "#DC2626",
      runnerUp: "Riverside AC",
      finalScore: "4–2",
      href: "Live Tournament.html",
    },
  ],

  // Cross-tournament headlines for the live ticker
  feed: [
    { tag: "Eastside Cup", text: "Owens nets her 8th of the tournament. Thunderhawks lead 2–1." },
    { tag: "Women's Premier", text: "Valley edge a five-goal thriller, 3–2 with 12 to play." },
    { tag: "Inter-Hostel", text: "Block C and Ridge locked at 0–0 after a cagey first half." },
    { tag: "Eastside Cup", text: "Quarterfinal draw confirmed — Thunderhawks face Kingfishers tonight." },
    { tag: "Freshers' 5s", text: "Registration closes tomorrow — 16 squads confirmed." },
  ],

  stats: {
    tournaments: 6,
    teams: 56,
    matchesToday: 11,
    goalsThisWeek: 84,
  },
};
